// actions/types.js

export const GET_ERRORS = 'GET_ERRORS';

export const READ_MEMBERS_REQUEST = 'READ_MEMBERS_REQUEST';
export const READ_MEMBERS_SUCCESS = 'READ_MEMBERS_SUCCESS';
export const READ_MEMBERS_FAIlED = 'READ_MEMBERS_FAIlED';