// actions/types.js

export const GET_ERRORS = 'GET_ERRORS';

export const READ_MEMBERS_REQUEST = 'READ_MEMBERS_REQUEST';
export const READ_MEMBERS_SUCCESS = 'READ_MEMBERS_SUCCESS';
export const READ_MEMBERS_FAILED = 'READ_MEMBERS_FAILED';

export const READ_PROFILE_REQUEST = 'READ_PROFILE_REQUEST';
export const READ_PROFILE_SUCCESS = 'READ_PROFILE_SUCCESS';
export const READ_PROFILE_FAILED = 'READ_PROFILE_FAILED';
